# Generated by Django 4.0.5 on 2022-08-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joke',
            name='content_info',
        ),
        migrations.AddField(
            model_name='joke',
            name='content',
            field=models.JSONField(default='{}', verbose_name='content'),
        ),
    ]
